version: 0.2

run-as: root

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install awscli
  build:
    commands:
      - api_gateway_id=$(aws apigateway get-rest-apis | jq -r '.[][] | select(.name=="apigateway-demo")|.id')
      - aws apigateway put-rest-api --rest-api-id $api_gateway_id --mode merge --body 'file://swagger.yaml'
      - aws apigateway create-deployment --rest-api-id $api_gateway_id --stage-name prod
