version: 0.2

run-as: root

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install awscli
  build:
    commands:
      - echo 'aws apigateway put-rest-api --rest-api-id 6znhu1vqp6 --mode merge --body 'file://swagger.yaml''
      - echo 'aws apigateway create-deployment --rest-api-id 6znhu1vqp6 --stage-name prod'
