version: 0.2

run-as: root

phases:
  install:
    runtime-versions:
      python: 3.7
      docker: 18
    commands:
      - pip install awscli
      - apt-get install -y jq
      - eval $(aws ecr get-login --no-include-email)
      - aws ecr create-repository --repository-name $REPO_NAME || echo "REPO EXISTS"
  build:
    commands:
      - GIT_HASH=$(git rev-parse --short HEAD)
      - REPO_URL=$(aws ecr describe-repositories --repository-names $REPO_NAME | jq .repositories[].repositoryUri)
      - docker build -t "$REPO_URL/$REPO_NAME:$GIT_HASH" .
      - docker push "$REPO_URL/$REPO_NAME:$GIT_HASH"
