version: 0.2

run-as: root

phases:
  install:
    runtime-versions:
      python: 3.7
      docker: 18
    commands:
      - pip install awscli
      - eval $(aws ecr get-login --no-include-email)
      - env | grep 'REPO_NAME'
      #- aws ecr create-repository --repository-name
  build:
    commands:
      - echo 'docker build -t test/imagename:tag'
      - echo 'docker push ecr-repo'
